pwd
ls -l .
echo "GOOGLE_CLOUD_DEPLOYMENT_SOURCE: $GOOGLE_CLOUD_DEPLOYMENT_SOURCE"
echo "GOOGLE_CLOUD_ENTRYPOINT_MODULE: $GOOGLE_CLOUD_ENTRYPOINT_MODULE"
echo "GOOGLE_CLOUD_ENTRYPOINT_OBJECT: $GOOGLE_CLOUD_ENTRYPOINT_OBJECT"
